### ISSUE TITLE
404 accessing the js file

### ISSUE THREAD

**Issue by psi-4ward** [home-assistant-tutorials/02.hello-world-card#1]
Hi,
I got an 404 and needed to whitelist the directory:

```yaml
default_config:
  whitelist_external_dirs:
    - /config/www
 ```

Probably worth a note?
